#path params
paths:
  base_path: "/Users/nafisneehal/Desktop/TrialBrain/TrialBrain"
  data_path:
    raw: "data/raw"
  log_path:
    data_loader: "logs/data_loader"
  output_path: "output"
  src_path: "src"
  test_path: "tests"

#Data Loading params
data_loader:
  fields:
    - NCTId
    - BriefTitle
    - Condition
    - BriefSummary
    - EligibilityCriteria
    - BaselineMeasureTitle
    - PrimaryOutcomeMeasure
    - InterventionName
    - StudyType
    - OverallStatus
  max_size: 70000
  base_url: https://clinicaltrials.gov/api/v2/studies
